### ISSUE TITLE
Bug Report: Setting name conflict

### ISSUE THREAD

**Issue by Bilka2** [TGNThump/AbandonedRuins#3]
### Overview
Hey, your settings aren't prefixed with your mod name. Doing that is a common courtesy as mods share the same setting namespace and mod names are unique, so everyone can keep their stuff separate. Because of this, your ["ruins-min-distance-from-spawn"](https://github.com/TGNThump/AbandonedRuins/blob/master/src/settings.ts#L4) setting interferes with the ["ruins-min-distance-from-spawn"](https://github.com/Bilka2/AbandonedRuins/blob/master/settings.lua#L11) of my mod, "The Ruins Mod" ("ruins" is its [old mod prefix](https://github.com/Bilka2/AbandonedRuins/blob/603b4ddce8584dc373b5e0141c1584febddb9426/info.json#L2)). It would be great if you could change your mod settings to include your mod name as a prefix so the conflict can be avoided.

### Enviroment
- Factorio [1.0]
- Abandoned Ruins [1.2.2]
- The Ruins Mod [1.0.0]

**Comment by benjamin-pilgrim** [comment]
Thanks for the report, and the explanation. I wasn't aware the settings were global. I plan to remove those settings in the next version, so it should no longer be an issue, but I'll make sure I change the prefix for any future settings.
