### ISSUE TITLE
Bug Report (Little Problem with Belt Layer)

### ISSUE THREAD

**Issue by xXDarkNovaXx** [TGNThump/AbandonedRuins#4]
### Overview
[Abandoned Ruins is generate Ruins in the second World Layer from Belt Layer
Since you can only dismantle things in the Second World Layer with a demolition plan, you cannot remove the runins generated in the Second World Layer, which is why they block the construction site]
https://mods.factorio.com/mod/beltlayer

Sry for Error i use a Translator

Real Overworld: https://prnt.sc/ukk1zm

Second Worldlayer only for Belt Layer: https://prnt.sc/ukk2lj

Report from Modpage: https://mods.factorio.com/mod/abandoned_ruins/discussion/5f6760320425dbea78c22ba8
I saw that they were active on Github so I posted it again
Since I thought you might not be that active on the mod side

My first post was on the mod page 3 days ago and I thought i look on Github times over

### Enviroment
- Factorio [1.0]
- Abandoned Ruins [1.2.2]
- [Belt Layer](To Much Mods ^^ |  I have more Mods but the Problem is only by Belt Leyer and Abandoned Ruins

**Comment by mspielberg** [comment]
If you could add an interface (LuaRemote) through which other mods could control which surfaces ruins are generated on, that would be ideal, I think. Alternatively, in your on_chunk_generated handler, just make sure the surface is "nauvis" before doing anything.

**Comment by benjamin-pilgrim** [comment]
The next version will only apply ruins to nauvis. Thanks for the report.

**Comment by xXDarkNovaXx** [comment]
The second world layer is on Nauvis
Can't you just say that he should just ignore the second world layer of Belt Layer?
Is it actually intended that ruins can only be dismantled by hand?

**Comment by xXDarkNovaXx** [comment]
After a long time I started Factorio again and I have to say that this problem still exists
The Problem is not the Planet  or other Planets from Space Exploration
Belt Layer is create a second World Layer on the Planet
I hope the attached file is at least helpful

https://drive.google.com/file/d/16XZFxWuKeTkV8z6PIu6-qIhhu3Esxolt/view?usp=sharing
